---
#
existing_lvs: "{%- if ((ansible_facts['lvm'] is defined) and (ansible_facts['lvm'] is mapping)) -%}
                 {{ ansible_facts['lvm'].lvs.keys() | list }}
               {%- else -%}
                 {{ [] }}
               {%- endif -%}"
existing_vgs: "{%- if ((ansible_facts['lvm'] is defined) and (ansible_facts['lvm'] is mapping)) -%}
                 {{ ansible_facts['lvm'].vgs.keys() | list }}
               {%- else -%}
                 {{ [] }}
               {%- endif -%}"
mount_points: "{{ ansible_facts['mounts'] | map(attribute='mount') | list }}"
