---
- name: Register with the RSVP server
  vars:
    arch_class: "{{ ansible_facts['architecture'] | upper }}"
    farm: "{{ inventory_hostname }}"
    os_class: "
      {%- set distribution = ansible_facts['distribution'] | upper -%}
      {%- if distribution == 'REDHAT' -%}
        RHEL{{ ansible_facts['distribution_major_version'] }}
      {%- else -%}
        {{ distribution }}{{ ansible_facts['distribution_major_version'] }}
      {%- endif -%}"
    classes:
      - ALBIREO
      - ALL
      - FARM
      - VDO
      - VFARM
      - "{{ os_class }}"
      - "{{ arch_class }}"
      # Replace omit with 'ALL' since omit stops working with Ansible in
      # Fedora 39. We use 'ALL' temporary, until the omit bug is fixed.
      # 'ALL' archive the same result since rsvp will ignore duplicate
      # value.
      - "{{ is_fedora | bool | ternary('FEDORA', 'ALL') }}"
      - "{{ ((is_fedora | bool) or (is_rhel8_or_later_family | bool))
            | ternary('LINUX-UDS', 'ALL') }}"
      - "{{ ((is_fedora | bool) or (is_rhel8_or_later_family | bool))
            | ternary('LINUX-VDO', 'ALL') }}"
      - "{{ is_performance_farm | bool | ternary('VDO-PMI', 'ALL') }}"
    class_list: "{{ classes | unique | join(',') }}"
  command: "rsvpclient --dhost {{ rsvp_server }} add {{ farm }} \
            --classes {{ class_list }}"
  become: yes
  become_user: "{{ bunsen_user }}"
  register: result
  failed_when:
    - result.rc != 0
    - not (result.stderr is search(inventory_hostname ~ '.* already exists'))
    - not (result.stderr is search(hostvars[inventory_hostname]['ansible_facts']['fqdn'] ~ '.* already exists'))
  changed_when: result.rc == 0

  # TODO: get the classes from the server.
  #       The list_classes --csv output is as:
  #         ALL,Default Class,class
  #         FARM,Default reservation class,class
  #         RHEL7, ,class
  #         VDO, ,class
  #         VFARM, ,class


