# Storage server variables.
---
_server_selection:
  distribution: "{{ ansible_facts['distribution'] + ansible_facts['distribution_version'] }}"
  architecture: "{{ ansible_facts['machine'] }}"
  environment:

# Server packages.
_server_packages:
  # Common to all distributions.
  - common:
    - targetd

server_packages: "{{ _server_packages | select_install(_server_selection) }}"
